#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

SYNOPKG_PKGDEST_OPENHAB_ENV="${SYNOPKG_PKGDEST}/app/app.env"

echo "HTTP_PORT=\"${OPENHAB_HTTP_PORT}\"" >> ${SYNOPKG_PKGDEST_OPENHAB_ENV}
echo "REDIS_PASSWORD=\"${OPENHAB_REDIS_PASSWORD}\"" >> ${SYNOPKG_PKGDEST_OPENHAB_ENV}

exit 0
