#!/bin/sh
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

echo "postinst"

echo "HTTP_PORT=\"${OPENHAB_HTTP_PORT}\"" >> app.env
echo "REDIS_PASSWORD=\"${REDIS_PASSWORD}\"" >> app.env

exit 0
